### PR TITLE
Fix #601 : handle the exception git command not found

### LINKED ISSUE #601: crane 安装出错——"crane:" is not a valid repository/tag
### Expected behavior
安装成功
### Actual behavior
安装过程报错
Building crane
ERROR: Error parsing reference: "crane:" is not a valid repository/tag

**or**

Building blackmamba
ERROR: Error parsing reference: "blackmamba:" is not a valid repository/tag

### Information about the Issue

docker-compose 在build crane和blackmamba时，没有正确读出TAG这个环境变量。
尝试将deploy/docker-compose.yml的两处:${TAG}删掉，问题解决

### Steps to reproduce the behavior

  1. CentOS7，安装配置好docker相关软件
  2. 下载解压crane。执行 CRANE_IP=172.18.24.69 ./bin/build-push-or-up.sh up

### PR DESCRIPTION
**Pull request by vitan**

### CODE REVIEW

File: bin/build-push-or-up.sh [hunk 1]
```diff
@@ -3,7 +3,11 @@
 set -e
 
 export REGISTRY_PREFIX=${REGISTRY_PREFIX:-""}
-export DEFAULT_TAG=`git log --pretty=format:'%h' -n 1`
+export DEFAULT_TAG=`git log --pretty=format:'%h' -n 1 2>/dev/null`
+if [ "x$DEFAULT_TAG" = "x" ]
+then
+    DEFAULT_TAG="emptytag"
```
Comment (xiaods) [inline bin/build-push-or-up.sh]: 这个啥意思

Comment (vitan) [inline bin/build-push-or-up.sh]: export DEFAULT_TAG=`git log --pretty=format:'%h' -n 1 2>/dev/null` will set DEFAULT_TAG="" maybe in case of *git command no found* . To fix it, I give a DEFAULT_TAG a default value *emptytag*

**Comment by vitan** [comment]
retest this please

**Comment by vitan** [comment]
retest this please

**Comment by vitan** [comment]
retest this please

**Comment by vitan** [comment]
retest this please

**Comment by vitan** [comment]
retest this please

File: bin/build-push-or-up.sh (hunk 1 above)
Comment (xiaods) [inline bin/build-push-or-up.sh]: but the emptytag is fake tag.

Comment (vitan) [inline bin/build-push-or-up.sh]: for development env only

Comment (xiaods) [inline bin/build-push-or-up.sh]: Need more info

Comment (xiaods) [inline bin/build-push-or-up.sh]: suppose use latest as DEFAULT_TAG @vitan

**Comment by xiaods** [comment]
LGTM
